### ISSUE TITLE
ORM: first steps

### ISSUE THREAD

**Issue by KozlovKV** [FIT-2024-RecALL/recall-back#4]
- [x] Окончательно определиться с ORM
- [x] Выбрать БД
- [x] Опираясь на SRS, составить базовые модели для БД

**Comment by AntonTsoy** [comment]
Выбранная мной ORM - SQLAlchemy. Окончательный выбор был между Алхимией и PonyORM (в частных бенчмарках она проявляла себя на голову лучше остальных). Но если мы начали ориентироваться на технологии популярные на рынке, то будем продолжать это делать. SQLAlchemy - одна из лучших в каждом показателе + это основной инструмент разработчиков из Т-Банка

**Comment by AntonTsoy** [comment]
На ветке [connect-orm](https://github.com/FIT-2024-RecALL/recall-back/tree/connect-orm) настроено использование синхронной `SQLite` базы данных через `SQLAlchemy ORM`. Для запуска приложения в директории проекта введи в терминале `fastapi dev sql_app/main.py`. НЕ ЗАБУДЬ настроить виртуальное окружение проекта перед запуском.

**Comment by AntonTsoy** [comment]
Немного почитал документацию [SQLModel](https://sqlmodel.tiangolo.com/). Это обертка над `SQLAlchemy` и `Pydantic`, которая должна помочь уменьшить дублирование кода, чтобы не писать модели и схемы для первого и второго соответственно.
Но решил, что мы не будем использовать этот инструмент. 1) Он ещё недостаточно стабилен (последняя версия - 0.0.22); 2) Он как бы должен избавлять нас от необходимости использовать чистую `алхимию`, но в [демо проекте](https://github.com/fastapi/full-stack-fastapi-template) FastAPI, в котором использовали `SQLModel`, не смогли обойтись без `SQLAlchemy`.

**Comment by KozlovKV** [comment]
Чтобы таска не висела целиком, создал для третьего пункта отдельную - #7

**Comment by AntonTsoy** [comment]
1. https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.asyncpg
2. https://pythonru.com/biblioteki/crud-sqlalchemy-orm
