### ISSUE TITLE
DB Models design and SQLAlchemy ORM integration

### ISSUE THREAD

**Issue by KozlovKV** [FIT-2024-RecALL/recall-back#7]
Форк от таска #4 для написания моделей БД на бэке

**Comment by AntonTsoy** [comment]
![изображение](https://github.com/user-attachments/assets/7318bdab-1a3d-4a9b-b3f3-9f1672be90ff)

**Comment by AntonTsoy** [comment]
Треть пути пройдена. Я понял, как организовывать связи между нашими таблица в БД, проверил, что все хорошо работает. Код на ветке `develop`, последний стабильный [коммит](https://github.com/FIT-2024-RecALL/recall-back/tree/eae64a5a22b53e49b3712cd86d4faf34da5e3f6f)

**Comment by AntonTsoy** [comment]
FastAPI 5 дней назад обновили документацию [SQL (Relational) Databases](https://fastapi.tiangolo.com/tutorial/sql-databases/)
